services:
  # Servicio de la aplicación FastAPI
  agora-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agora-fastapi
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/iph_database.db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - APP_NAME=${APP_NAME:-Sistema IPH}
      - VERSION=${VERSION:-1.0.0}
      - DEBUG=${DEBUG:-False}
    volumes:
      # Montar volumen para persistir la base de datos
      - ./data:/app/data
      # Opcional: montar el código para desarrollo (comentar para producción)
      # - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - agora-network

  # Servicio opcional de base de datos PostgreSQL (comentado por defecto)
  # Descomenta si quieres usar PostgreSQL en lugar de SQLite
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: agora-postgres
  #   environment:
  #     POSTGRES_DB: agora_db
  #     POSTGRES_USER: agora_user
  #     POSTGRES_PASSWORD: agora_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped
  #   networks:
  #     - agora-network

networks:
  agora-network:
    driver: bridge

# Volúmenes para persistencia de datos
volumes:
  postgres_data: